obstacle_range: 2.5
raytrace_range: 6.0
#footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
#footprint_inflation: 0.01
robot_radius: 0.25
max_obstacle_height: 0.6
min_obstacle_height: 0.0
#observation_sources: scan
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
observation_sources: base_lidar
base_lidar: {
    data_type: LaserScan,
    topic: /scan, 
    marking: true, 
    clearing: true
    }
# if set to false,then obstacle layer take unknow space to be free.
obstacle_layer:
   track_unknown_space: true
